# Generated by Django 4.1.2 on 2022-10-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelPredictor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Pregnancies", models.IntegerField()),
                ("Glucose", models.IntegerField()),
                ("BloodPressure", models.IntegerField()),
                ("SkinThickness", models.IntegerField()),
                ("Insulin", models.IntegerField()),
                ("BMI", models.FloatField()),
                ("DiabetesPedigreeFunction", models.FloatField()),
                ("Age", models.IntegerField()),
            ],
        ),
    ]
